=== lamao/lamaopzks/resourses/configuration/ConfigurationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="configuration" >
    	<xs:complexType>
    		<xs:all>
    			<xs:element name="renderer" type="xs:string" />
    			<xs:element name="queue1" type="xs:string" />
    			<xs:element name="queue2" type="xs:string" />
    			<xs:element name="queue3" type="xs:string" />
    			<xs:element name="storage" type="xs:string" />
    			<xs:element name="planner1" type="xs:string" />
    			<xs:element name="planner-strategy1" type="xs:string" />
    			<xs:element name="planner2" type="xs:string" />
    			<xs:element name="planner-strategy2" type="xs:string" />
    			<xs:element name="default-look" type="xs:string" />
    			<xs:element name="look-and-feel" type="xs:string" />
    			<xs:element name="gant-renderer" type="xs:string" />
    			<xs:element name="immerse-dialog" type="xs:string" />
    			<xs:element name="generate-dialog" type="xs:string" />
    			<xs:element name="language" type="xs:string" />
    		</xs:all>
    	</xs:complexType>
    </xs:element>
    
    
</xs:schema>

=== lamao/lamaopzks/resourses/configuration/Configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="ConfigurationSchema.xsd">
    
        <renderer>pzks.ui.renderer.PZKSLamaoRenderer</renderer>
        <queue1>pzks.model.planners.queue.PZKSVariant2QueuePlanner</queue1>
        <queue2>pzks.model.planners.queue.PZKSVariant9QueuePlanner</queue2>
        <queue3>pzks.model.planners.queue.PZKSVariant11QueuePlanner</queue3>
        <storage>resourses/configuration/LamaoResourses.xml</storage>
        <planner1>pzks.model.planners.assignment.PZKSVariant3AssignmentPlanner</planner1>
        <planner-strategy1>pzks.model.planners.assignment.PZKSPreactStrategy</planner-strategy1>
        <planner2>pzks.model.planners.assignment.PZKSVariant5AssignmentPlanner</planner2>
        <planner-strategy2>pzks.model.planners.assignment.PZKSPreactStrategy</planner-strategy2>
        <default-look>true</default-look>
        <look-and-feel>com.nilo.plaf.nimrod.NimRODLookAndFeel</look-and-feel>
        <gant-renderer>pzks.ui.renderer.PZKSLamaoGantRenderer</gant-renderer>
        <immerse-dialog>pzks.ui.dialogs.PZKSLamaoImmerseDialog</immerse-dialog>
        <generate-dialog>pzks.ui.dialogs.PZKSLamaoGenerateDialog</generate-dialog>
        <language>ua</language>
        
</configuration>
